list.of.packages <- c("lintr", "covr", "pkgbuild", "roxygen2", "Rcpp", "testthat")
new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages)
# lintr::use_lintr(type = "tidyverse")
system2("autoreconf")
Rcpp::compileAttributes()
devtools::document(roclets = c('rd', 'collate', 'namespace'))
l <- lintr::lint_package()
print(l)
stopifnot(length(l)==0)
check_res <- devtools::check()
stopifnot(max(sapply(check_res[c("errors", "warnings", "notes")], length))==0)
devtools::install()
cov <- covr::package_coverage()
print(cov)
stopifnot(covr::percent_coverage(cov)==100)
#covr::report(cov)

devtools::build_manual(path = "build")
devtools::build(path = "build")
devtools::build(path = "build", binary = TRUE)
