# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ecdf2 <- function(b, B, use_fft) {
    .Call('_crossingprobability_ecdf2', PACKAGE = 'crossingprobability', b, B, use_fft)
}

