# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ecdf1_mns2016_b <- function(b) {
    .Call(`_crossingprobability_ecdf1_mns2016_b`, b)
}

ecdf1_mns2016_B <- function(B) {
    .Call(`_crossingprobability_ecdf1_mns2016_B`, B)
}

ecdf1_new_B <- function(B) {
    .Call(`_crossingprobability_ecdf1_new_B`, B)
}

ecdf1_new_b <- function(b) {
    .Call(`_crossingprobability_ecdf1_new_b`, b)
}

ecdf2 <- function(b, B, use_fft) {
    .Call(`_crossingprobability_ecdf2`, b, B, use_fft)
}

